name: KeypointNeRF
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.1
  - argcomplete=1.12.3
  - astroid=2.9.0
  - blas=1.0
  - ca-certificates
  - colorama=0.4.4
  - cycler=0.11.0
  - freetype=2.10.4
  - icu=67.1
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - isort=5.10.1
  - jbig=2.1
  - jpeg=9d
  - kiwisolver=1.3.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libtiff=4.3.0
  - libuv=1.42.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mccabe=0.6.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=3.0.0
  - pillow=8.4.0
  - pip=21.3.1
  - platformdirs=2.3.0
  - pylint=2.12.2
  - pyparsing=3.0.6
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - readline=8.1
  - setuptools=59.4.0
  - six=1.16.0
  - sqlite=3.37.0
  - tensorboardx=2.4
  - tk=8.6.11
  - toml=0.10.2
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - tornado=6.1
  - typing-extensions=4.0.1
  - typing_extensions=4.0.1
  - wheel=0.37.0
  - wrapt=1.13.3
  - xz=5.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - astunparse==1.6.3
    - async-timeout==4.0.1
    - attrs==21.2.0
    - cachetools==4.2.4
    - certifi==2021.10.8
    - charset-normalizer==2.0.9
    - chumpy==0.70
    - configargparse==1.5.3
    - flatbuffers==2.0
    - freetype-py==2.2.0
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - future==0.18.2
    - gast==0.4.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.42.0
    - h5py==3.6.0
    - idna==3.3
    - imageio==2.13.3
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kornia==0.5.11
    - libclang==12.0.0
    - lpips==0.1.4
    - markdown==3.3.6
    - multidict==5.2.0
    - networkx==2.6.3
    - oauthlib==3.1.1
    - opencv-python==4.5.4.60
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.4
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pyglet==1.5.21
    - pyopengl==3.1.0
    - pyrender==0.1.45
    - pytorch-lightning==1.6.0
    - pytz==2021.3
    - pywavelets==1.2.0
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-image==0.19.0
    - scipy==1.7.3
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - termcolor==1.1.0
    - test-tube==0.7.5
    - tifffile==2021.11.2
    - torch==1.11.0
    - torchmetrics==0.6.1
    - tqdm==4.62.3
    - trimesh==3.9.36
    - urllib3==1.26.7
    - warmup-scheduler==0.3
    - werkzeug==2.0.2
    - yarl==1.7.2